const express = require('express');
const router = express.Router();

const roleRoutes = require('./role.routes');
const userRoutes = require('./user.routes');
const employeeRoutes = require('./employee.routes');
const agentRoutes = require('./agents.routes');
const ledgerHeadRoutes = require('./ledgerHead.routes');
const partiesRoutes = require('./parties.routes');
const categoriesRoutes = require('./categoriesCategories.routes');
const productRoutes = require('./product.routes');
const stateRoutes = require('./states.routes');
const transportRoutes = require('./transports.routes');
const taxRoutes = require('./taxes.routes');
const tdsRateRoutes = require('./tdsRates.routes');
const expenseRoutes = require('./expenseCategories.routes');
const actualExpenseRoutes = require('./expense.routes');
const termRoutes = require('./term.routes');
const bankRoutes = require('./bank.routes');
const cashAndBankRoutes = require('./cashAndBank.routes');
const ordersRoutes = require('./orders.routes');
const userOrdersRoutes = require('./userOrders.routes');
const salesRoutes = require('./sales.routes');
const salesReturnRoutes = require('./salesReturn.routes');
const receiptRoutes = require('./receipt.routes');
const purchaseRoutes = require('./purchase.routes');
const purchaseReturnRoutes = require('./purchaseReturn.routes');
const paymentsRoutes = require('./payments.routes');
const adminRoutes = require('./admin.routes');
const bannerRoutes = require('./banner.routes');
const contactRoutes = require('./contact.routes');
const notificationRoutes = require('./notification.routes');
const storyRoutes = require('./story.routes');

const { adminVerifyToken } = require('../../helper/admin.verifyToken');

router.use('/roles', adminVerifyToken, roleRoutes);
router.use('/users', adminVerifyToken, userRoutes);
router.use('/employees', adminVerifyToken, employeeRoutes);
router.use('/agents', adminVerifyToken, agentRoutes);
router.use('/ledger-heads', adminVerifyToken, ledgerHeadRoutes);
router.use('/parties', adminVerifyToken, partiesRoutes);
router.use('/categories', adminVerifyToken, categoriesRoutes);
router.use('/products', adminVerifyToken, productRoutes);
router.use('/states', adminVerifyToken, stateRoutes);
router.use('/transports', adminVerifyToken, transportRoutes);
router.use('/taxes', adminVerifyToken, taxRoutes);
router.use('/tds-rates', adminVerifyToken, tdsRateRoutes);
router.use('/expense-categories', adminVerifyToken, expenseRoutes);
router.use('/expenses', adminVerifyToken, actualExpenseRoutes);
router.use('/terms', adminVerifyToken, termRoutes);
router.use('/banks', adminVerifyToken, bankRoutes);
router.use('/cash-banks', adminVerifyToken, cashAndBankRoutes);
router.use('/orders', adminVerifyToken, ordersRoutes);
router.use('/user-orders', adminVerifyToken, userOrdersRoutes);
router.use('/sales', adminVerifyToken, salesRoutes);
router.use('/sales-returns', adminVerifyToken, salesReturnRoutes);
router.use('/receipts', adminVerifyToken, receiptRoutes);
router.use('/purchases', adminVerifyToken, purchaseRoutes);
router.use('/purchase-returns', adminVerifyToken, purchaseReturnRoutes);
router.use('/payments', adminVerifyToken, paymentsRoutes);
router.use('/banners', adminVerifyToken, bannerRoutes);
router.use('/contacts', adminVerifyToken, contactRoutes);
router.use('/notifications', adminVerifyToken, notificationRoutes);
router.use('/stories', adminVerifyToken, storyRoutes);
router.use('/', adminRoutes);
       
module.exports = router;
